name: React CI/CD Workflow

on:
  push:
    branches:
      - main # Jalankan workflow saat ada push ke branch 'main'
  pull_request:
    branches:
      - main # Jalankan workflow saat ada pull request ke branch 'main'

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru yang di-host oleh GitHub

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action untuk mengambil kode dari repositori

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Action untuk menyiapkan lingkungan Node.js
      with:
        node-version: '20' # Gunakan versi Node.js yang Anda gunakan (misalnya 18, 20, 22)
        cache: 'npm' # Mengaktifkan caching untuk dependensi npm

    - name: Install dependencies
      run: npm ci # Menginstal dependensi. 'npm ci' lebih baik untuk CI daripada 'npm install'

    - name: Run ESLint
      run: npm run lint # Asumsi Anda memiliki script 'lint' di package.json Anda
      # Contoh: "lint": "eslint . --ext js,jsx,ts,tsx --report-unused-disable-directives --max-warnings 0"

    - name: Run tests
      run: npm test -- --watchAll=false # Asumsi Anda memiliki script 'test' di package.json Anda
      # '--watchAll=false' penting untuk CI agar tidak stuck di mode watch

    - name: Build React app
      run: npm run build # Asumsi Anda memiliki script 'build' di package.json Anda
      env:
        CI: true # Mengatur CI=true untuk mencegah peringatan yang dianggap sebagai error di beberapa setup